android_binary(
	name = 'app',
	manifest = 'AndroidManifest.xml',
	keystore = ':debug_keystore',
	deps = [
		'//app:app',
		'//app:res',
	],
)

keystore(
	name = 'debug_keystore',
	store = 'debug.keystore',
	properties = 'debug.keystore.properties',
)

project_config(src_target = ':app')
